[app]
name = "maudit"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8090"

[app.grpc]
host = "127.0.0.1"
port = "18090"

[keyauth]
host = "127.0.0.1"
port = "18050"
client_id = "asdf"
client_secret = "asdfdsf"

[mongodb]
endpoints = ["127.0.0.1:27017"]
username = "maudit"
password = "123456"
database = "maudit"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"